#!/bin/bash

# Muda para o diretório do repositório local
cd ~/projects/testes/config-test

# Executa o comando para fazer o pull
git pull
ssh user@host '~/projects/testes/config-test/hooks/post-receive'
