#!/bin/bash
echo "Recebido push, fazendo o pull do repositório..."
cd ~/projects/testes/config-test.git
git --work-tree=~/projects/testes --git-dir=~/projects/testes/config-test.git pull origin master
ssh user@host '~/projects/testes/config-test/hooks/post-receive'
