name: Pull Repo

on:
  push:
    branches: [ main ] # Altere "main" para a branch principal do seu repositório

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pull Repo
      run: |
        cd ${{ github.workspace }}/deploy/config-test # Substitua pelo caminho para o seu repositório local
        git pull