name: Atualização do repositório

on:
  push:
    branches: [main]

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Atualização do repositório
        run: |
          cd ${{ github.workspace }}
          git pull
