name: Pull Repo

on:
  push:
    branches: [ main ] # Altere "main" para a branch principal do seu repositório

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pull Repo
      run: |
        cd ~/deploy/config-test # Substitua pelo caminho para o seu repositório local
        git pull