name: Build and Deploy Assets
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Assets
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout the commit
        uses: actions/checkout@v2

      - name: Deploy
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          src_dir: build
          target_owner: yurevsal
          target_repo: config-test
          target_dir: src/assets
          target_branch: master # default
